#ifndef CCL__RANGE__H
#define CCL__RANGE__H

#define cc_range(...) \
  (((((((((((((((((((((((__RANGE_012343210_LL)))))))))))))))))))))), (__VA_ARGS__))

#define __RANGE_012343210_LL(...) _RANGE_01201_LL
#define _RANGE_01201_LL(...)
#define HIDE_RANGE() RANGE_STATE

#define RANGE_CHECK(ARG) IF_ELSE(PARENTHESIS(ARG), IF_ELSE(PARENTHESIS(ALIAS____(CHOOSE_ARG, __EXPAND_1 ARG)), __EXPAND64(RANGE_STATE((0), ALIAS____(CHOOSE_ARG, __EXPAND_1 ARG))))(0))(0)

#define RANGE_UNTRUE 0

#define RANGE_TRUE_1(STATE, PAREN)\
  PUSH(HIDE_RANGE)()((__EXPAND_1 STATE, 0), __EXPAND_1 PAREN)
#define RANGE_TRUE_0(...) 0

#define RANGE_STATE(STATE, PAREN)\
  IF_ELSE(NOT(NUMPAREN_IS_23(NUMAR___G(__EXPAND_1 STATE))),\
	  CAT(RANGE_TRUE_, PARENTHESIS(PAREN))(STATE, PAREN))\
    (IF_ELSE(AND(NOT(PARENTHESIS(PAREN)), NOT(FIND_PAREN_PAREN(PAREN)))(1), IF_ELSE(NOT(CHECK_ARG(PAREN()())), 1)(0))(0))

#define NUMPAREN_IS_23(VAR_23) NOT(CAT(PAREN_AT_, VAR_23))
#define PAREN_AT_23 0

#endif
