#include "utilmacros.h"
#include "typesAndGroupsmacro.h"
#include "numargs.h"
#include "../debug/errormessage.h"

#if __GNUC__
/*#pragma GCC diagnostic ignored "-Wunused-macros"*/
#endif
static char name__[5] = "ARRAY";

/* ARRAY RECURSIVE MACROS */
#define __EXPAND_N_LOOP_IF_ELSE(CONDITION, EXP, ...)	\
    IF_TRUE___EXPAND_AND_REPEAT_ARRAY(CONDITION, EXP, __VA_ARGS__)\
    UNLESS(NOT(CONDITION))
/**/
#define IF_TRUE___EXPAND_AND_REPEAT_ARRAY(CONDITION, EXP, ...)	\
  CAT(SWITCH(CONDITION), CAT(REPEAT_, BOOL(CONDITION)))		\
    (EXP, __VA_ARGS__)

#define HIDE_ARRAY() ARRAY_ARGS
/* recursive */

/* if member marks a pointer wrap in {} else dont wrap, recall */
#define MERGE_AND_RECALL_1(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, STATE, ARG, ...)	\
  PUSH(HIDE_ARRAY)()(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, 1, IF_ELSE(ARR_MARKER, (__EXPAND_1 STATE, (TYPE[]){__EXPAND_1 ARG}))((__EXPAND_1 STATE, __EXPAND_1 ARG)), __VA_ARGS__)

#define MERGE_AND_RECALL_0(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, STATE, ARG, ...) \
  PUSH(HIDE_ARRAY)()(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, 1, IF_ELSE(ARR_MARKER, ((TYPE[]){__EXPAND_1 ARG}))(ARG), __VA_ARGS__)

#define RECALL_ARRAY(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, APD, STATE, ARG, ...) CAT(MERGE_AND_RECALL_, BOOL(APD))(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, STATE, ARG, __VA_ARGS__)

#define __EXPAND_1REPEAT_1(EXP, ...)			\
  EXP RECALL_ARRAY(__VA_ARGS__)
#define __EXPAND_0REPEAT_0(...)

#define ARRAY(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, ...)			\
  IF_ELSE(PARENTHESIS(OBJ), LOGMSG(SIGOBJPAREN, OBJ))(			\
    CAT(__EXPAND_, NOT(PARENTHESIS(OBJ)))(CAT(__EXPAND_, CHECK_ARG(OBJ)) \
    (__VA_OPT__(IF_ELSE(CHECK_ARG(FUNC), __EXPAND4(ARRAY_ARGS(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, 0, (), __VA_ARGS__))) \
		((NO_FUNCTION_PASSED_TO_ARRAY)0)))))

#define DO_NOTHING(...)
/* __ARRAY_ARGS__ */
#define ARRAY_ARGS(FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, APD, STATE, ARG, ...) \
  __EXPAND_N_LOOP_IF_ELSE(CHECK_ARG(ARG), IF_ELSE(PARENTHESIS(ARG), CAT(ASSERT_ARG_, CHECK_ARG(__EXPAND_1 ARG)) (SIGUNUSED, ARG, CAT(ARG_VARGS_, CHECK_ARG(__EXPAND_1 ARG)) (DO_NOTHING(0), __VA_ARGS__))) (ASSERT_ARG_0(SIGBOUND, ARG, __VA_ARGS__)), FUNC, OBJ, MEMTYPE, ARR_MARKER, TYPE, APD, STATE, ARG, __VA_ARGS__) \
    (IF_ELSE(NOT(CHECK_ARG(__VA_ARGS__)), __EXPAND_1 STATE/* TODO: create array here*/)(ASSERT_ARG_0(SIGEMPTY, ","ARG, __VA_ARGS__)))
